//////////////////////////////////
//          LOCALHOST           //
//////////////////////////////////
### Get all contacts
GET http://localhost:8080/contacts

### Get contact by ID
GET http://localhost:8080/contacts/687aa30e0fbc489862c7b163

### Create a new contact
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "testType": "personality",
  "testName": "PAI",
  "questions": [
    {
      "question": "Are you comfortable in social situations?",
      "questionType": "single choice",
      "options": [
        {
          "optionNumber": 0,
          "option": "Strongly Disagree",
          "isCorrect": false
        },
        {
          "optionNumber": 1,
          "option": "Disagree",
          "isCorrect": false
        },
        {
          "optionNumber": 2,
          "option": "Neutral",
          "isCorrect": false
        }
      ]
    },
    {
      "question": "Describe your biggest strength",
      "questionType": "text",
      "options": []
    }
  ]
}


### Update a contact by ID
PUT http://localhost:8080/contacts/687aa30e0fbc489862c7b163
Content-Type: application/json

{
  "testType": "personality",
  "testName": "PAI",
  "questions": [
    {
      "question": "Are you comfortable in social situations?",
      "questionType": "single choice",
      "options": [
        {
          "optionNumber": 0,
          "option": "Strongly Disagree",
          "isCorrect": false
        },
        {
          "optionNumber": 1,
          "option": "Disagree",
          "isCorrect": false
        },
        {
          "optionNumber": 2,
          "option": "Neutral",
          "isCorrect": false
        }
      ]
    },
    {
      "question": "Describe your biggest strength",
      "questionType": "text",
      "options": []
    }
  ]
}

### Delete a contact by ID
DELETE http://localhost:8080/contacts/687aa30e0fbc489862c7b163


//////////////////////////////////
//          PRODUCTION          //
//////////////////////////////////
### Get all contacts
GET https://get-contacts-api.onrender.com/contacts

### Get contact by ID
GET https://get-contacts-api.onrender.com/contacts/687aa30e0fbc449862c7b263

### Create a new contact
POST https://get-contacts-api.onrender.com/contacts/
Content-Type: application/json

{
  "testType": "personality",
  "testName": "PAI",
  "questions": [
    {
      "question": "Are you comfortable in social situations?",
      "questionType": "single choice",
      "options": [
        {
          "optionNumber": 0,
          "option": "Strongly Disagree",
          "isCorrect": false
        },
        {
          "optionNumber": 1,
          "option": "Disagree",
          "isCorrect": false
        },
        {
          "optionNumber": 2,
          "option": "Neutral",
          "isCorrect": false
        }
      ]
    },
    {
      "question": "Describe your biggest strength",
      "questionType": "text",
      "options": []
    }
  ]
}


### Update a contact by ID
PUT https://get-contacts-api.onrender.com/contacts/6975244152d93b337bf84c58
Content-Type: application/json

{
  "testType": "personality",
  "testName": "PAI",
  "questions": [
    {
      "question": "Are you comfortable in social situations?",
      "questionType": "single choice",
      "options": [
        {
          "optionNumber": 0,
          "option": "Strongly Disagree",
          "isCorrect": false
        },
        {
          "optionNumber": 1,
          "option": "Disagree",
          "isCorrect": false
        },
        {
          "optionNumber": 2,
          "option": "Neutral",
          "isCorrect": false
        }
      ]
    },
    {
      "question": "Describe your biggest strength",
      "questionType": "text",
      "options": []
    }
  ]
}


### Delete a contact by ID
DELETE https://get-contacts-api.onrender.com/contacts/6975244152d93b337bf84c58
